Entities/MarcaProducto.cs
using System.ComponentModel.DataAnnotations;

namespace ConexionEF.Entities
{
    public class MarcaProducto
    {
        public MarcaProducto()
        {
        }

        public Guid Id {get;set;}
        [StringLength(100)]
        [Required]
        public string Nombre {get;set;}
        [StringLength(250)]
        public string Descripcion {get;set;}
    }
}

Entities/TipoProducto.cs
using System.ComponentModel.DataAnnotations;

namespace ConexionEF.Entities
{
    public class TipoProducto
    {
        public TipoProducto()
        {

        }

        public Guid Id {get;set;}
        [StringLength(100)]
        [Required]
        public string Nombre {get;set;}
        [StringLength(250)]
        public string Descripcion {get;set;}

    }
}

Models/ErrorViewModel.cs
namespace ConexionEF.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/MarcaModel.cs
namespace ConexionEF.Models
{
    public class MarcaModel
    {
        public MarcaModel()
        {
        }

        public Guid Id {get;set;}
     
        public string Nombre {get;set;}
        
        public string Descripcion {get;set;}
    }
}

Models/ProductoModel.cs
namespace ConexionEF.Models
{
    public class ProductoModel
    {
        public ProductoModel()
        {
        }

        public Guid Id {get;set;}
     
        public string Nombre {get;set;}
        
        public string Descripcion {get;set;}
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ConexionEF.Models;

namespace ConexionEF.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/MarcasController.cs
using ConexionEF.Entities;
using ConexionEF.Models;
using Microsoft.AspNetCore.Mvc;

namespace ConexionEF.Controllers
{
        public class MarcasController : Controller
    {
        public readonly ApplicationDbContext _context;
        public MarcasController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult MarcaAdd()
        {
            MarcaProducto entity = new MarcaProducto();
            entity.Id = new Guid();
            entity.Nombre = "Coca-Cola";
            entity.Descripcion = "Marca de grupo Femsa";

            _context.MarcasProductos.Add(entity);
            _context.SaveChanges();

            return View();
        }

        public IActionResult MarcaList()
        {
            List<MarcaModel> list = 
            _context.MarcasProductos
            .Select(m => new MarcaModel()
            {
                Id = m.Id,
                Nombre = m.Nombre,
                Descripcion = m.Descripcion
            }
            )
            .ToList();

            return View(list);
        }

        public IActionResult MarcaEdit(Guid Id)
        {
            // Id = new Guid("43050F98-CA21-4A3A-BFF0-08DC8B2ECE47");

            MarcaProducto entity = _context.MarcasProductos
            .Where(m => m.Id == Id)
            .FirstOrDefault();

            entity.Nombre = "Pepsi";
            entity.Descripcion = "Grupo PEPSICO";

            _context.MarcasProductos.Update(entity);
            _context.SaveChanges();

            return View();
        }

        public IActionResult MarcaDelete()
        {
            return View();
        }
    }
}

Controllers/ProductoController.cs
using ConexionEF;
using ConexionEF.Entities;
using ConexionEF.Models;
using Microsoft.AspNetCore.Mvc;

public class ProductoController : Controller
{
    // public readonly ApplicationDbContext _context;
    public readonly ApplicationDbContext _context;
        public ProductoController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult ProductoAdd()
        {
            TipoProducto entity = new TipoProducto();
            entity.Id = new Guid();
            entity.Nombre = "Refresco";
            entity.Descripcion = "Bebida sabor naranja";

            _context.TiposProductos.Add(entity);
            _context.SaveChanges();

            return View();
        }

        public IActionResult ProductoList()
        {
            List<ProductoModel> list = 
            _context.TiposProductos
            .Select(m => new ProductoModel()
            {
                Id = m.Id,
                Nombre = m.Nombre,
                Descripcion = m.Descripcion
            }
            )
            .ToList();

            return View(list);
        }

        public IActionResult ProductoEdit(Guid Id)
        {
            // Id = new Guid("43050F98-CA21-4A3A-BFF0-08DC8B2ECE47");

            TipoProducto entity = _context.TiposProductos
            .Where(m => m.Id == Id)
            .FirstOrDefault();

            entity.Nombre = "jugo";
            entity.Descripcion = "Jumex";

            _context.TiposProductos.Update(entity);
            _context.SaveChanges();

            return View();
        }

        public IActionResult MarcaDelete()
        {
            return View();
        }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Marcas/MarcaList.cshtml
@model List<MarcaModel>

<h1>Marcas de Productos</h1>

<a class = "btn btn primary" asp-action="MarcaAdd" asp-controller="Marcas">Agregar Marca</a>

<table class="table">
    <thead>
        <tr>
        <th>Nombre</th>
        <th>Descripcion</th>
        <th>Acciones</th>
        </tr>
       
    </thead>
    <tbody>
        @foreach(var m in Model)
        {
            <tr>
                <td>@m.Nombre</td>
                <td>@m.Descripcion</td>
                <td>
                    <a class = "btn btn-secundary" 
                    asp-action="MarcaEdit" 
                    asp-controller="Marcas" 
                    asp-route-id="@m.Id">Editar</a>

                    <a class = "btn btn-secundary" 
                    asp-action="MarcaDelete" 
                    asp-controller="Marcas" 
                    asp-route-id="@m.Id">Borrar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Productos/ProductoList.cshtml
@model List<ProductoModel>

<h1>Tipos de Productos</h1>

<a class = "btn btn primary" asp-action="ProductoAdd" asp-controller="Producto">Agregar Producto</a>

<table class="table">
    <thead>
        <tr>
        <th>Nombre</th>
        <th>Descripcion</th>
        <th>Acciones</th>
        </tr>
       
    </thead>
    <tbody>
        @foreach(var m in Model)
        {
            <tr>
                <td>@m.Nombre</td>
                <td>@m.Descripcion</td>
                <td>
                    <a class = "btn btn-secundary" 
                    asp-action="ProductoEdit" 
                    asp-controller="Producto" 
                    asp-route-id="@m.Id">Editar</a>

                    <a class = "btn btn-secundary" 
                    asp-action="ProductoDelete" 
                    asp-controller="Producto" 
                    asp-route-id="@m.Id">Borrar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ConexionEF</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ConexionEF.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ConexionEF</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Marcas" asp-action="MarcaList">Marcas de Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="ProductoList">Tipos de Productos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ConexionEF - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>